development: &default
  adapter: postgresql
  database: radiant_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: radiant_test

production:
  <<: *default
  database: radiant_production
