version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
  radiant:
    build: .
    command:
      - "script/server"
      - "-p"
      - "3000"
      - "-b"
      - "0.0.0.0"
    environment:
      - RAILS_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db
